[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='9ff976bbb19bb08a3d58e2803c0152b1a59a194438ecb6e86a34158aadce1d5e'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
